# Generated by Django 3.0.5 on 2020-05-03 21:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.TextField()),
                ('card_type', models.TextField()),
                ('credit_rating', models.TextField()),
                ('intro_text', models.TextField(blank=True)),
                ('cta_text', models.TextField(blank=True)),
                ('card1', jsonfield.fields.JSONField(null=True)),
                ('card2', jsonfield.fields.JSONField(null=True)),
                ('error_text', models.TextField()),
                ('maintenance_text', models.TextField()),
            ],
        ),
    ]
