# Generated by Django 3.0.5 on 2020-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200503_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='card_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='credit_rating',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='cta_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='error_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='intro_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='maintenance_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='updated_date',
            field=models.CharField(max_length=250),
        ),
    ]
